platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build

test: off
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: szQNdmLNz3ORHJoiuk+gvPiBVSdRAnY59vzCeNDLYdy2pM/GEgMx6as8QH9xJHw+
  artifact: /build\\.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
branches:
  only:
    - master
